[package]
name = "fidelity-macros"
description = "The guarded!() macro for the fidelity runtime tamper detection library."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories = ["development-tools::procedural-macro-helpers", "security"]

[lib]
proc-macro = true

[dependencies]
fidelity-cipher.workspace = true

[lints]
workspace = true
