[package]
name = "fidelity-package-check"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[workspace]

[dependencies]
fidelity = { path = "packages/fidelity-@VERSION@", features = ["serde", "tracing"] }

[patch.crates-io]
fidelity-cipher = { path = "packages/fidelity-cipher-@VERSION@" }
fidelity-core = { path = "packages/fidelity-core-@VERSION@" }
fidelity-detect = { path = "packages/fidelity-detect-@VERSION@" }
fidelity-engine = { path = "packages/fidelity-engine-@VERSION@" }
fidelity-formats = { path = "packages/fidelity-formats-@VERSION@" }
fidelity-macros = { path = "packages/fidelity-macros-@VERSION@" }
fidelity-probe-android = { path = "packages/fidelity-probe-android-@VERSION@" }
fidelity-probe-apple = { path = "packages/fidelity-probe-apple-@VERSION@" }
fidelity-probe-linux = { path = "packages/fidelity-probe-linux-@VERSION@" }
fidelity-probe-windows = { path = "packages/fidelity-probe-windows-@VERSION@" }
fidelity-types = { path = "packages/fidelity-types-@VERSION@" }
