[package]
name = "fidelity"
description = "Detect hostile changes to an application's runtime environment, and apply a host-selected response."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
fidelity-cipher = { path = "../fidelity-cipher", version = "0.0.0" }

[dependencies]
fidelity-cipher = { path = "../fidelity-cipher", version = "0.0.0" }
fidelity-core = { path = "../fidelity-core", version = "0.0.0" }
fidelity-detect = { path = "../fidelity-detect", version = "0.0.0" }
fidelity-engine = { path = "../fidelity-engine", version = "0.0.0" }
fidelity-macros = { path = "../fidelity-macros", version = "0.0.0" }
fidelity-types = { path = "../fidelity-types", version = "0.0.0" }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
fidelity-probe-apple = { path = "../probe/fidelity-probe-apple", version = "0.0.0" }

[target.'cfg(target_os = "linux")'.dependencies]
fidelity-probe-linux = { path = "../probe/fidelity-probe-linux", version = "0.0.0" }

[target.'cfg(target_os = "android")'.dependencies]
fidelity-probe-android = { path = "../probe/fidelity-probe-android", version = "0.0.0" }

[lints]
workspace = true
