#!/bin/sh
# Runs the controls that this machine can reach, and writes the generated
# record that docs/plan/05-verification.md asks for.
#
#     evidence/run.sh [record path]
#
# The record is a tab-separated file, one row for each control, with four
# columns: system, control, result, detail. A result is one of
#
#     pass      the control ran here and gave the answer it must give
#     fail      the control ran here and gave another answer
#     skipped   this machine cannot reach the system, and the detail says why
#     manual    a person runs this control, and the detail says where the
#               result lives in evidence/README.md
#
# The skipped rows carry the weight. A record that lists only what passed reads
# as complete coverage, and no machine reaches every system that Fidelity
# supports. This one names what it could not run.
#
# The script leaves output for each control under target/evidence/, and it
# exits non-zero when any control that ran gave a wrong answer.
set -u

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
RECORD=${1:-$ROOT/evidence/record.tsv}
OUT=$ROOT/target/evidence
FAILED=0

# Every target that a probe crate builds for. The cross-check is what proves
# that a change to a capability trait still compiles every platform.
TARGETS="aarch64-apple-darwin aarch64-apple-ios aarch64-linux-android aarch64-unknown-linux-gnu x86_64-pc-windows-msvc"

# A digest of the right shape, for the build rules that must refuse a value.
DIGEST=9f3a1c0e5b7d2846a09f3a1c0e5b7d2846a09f3a1c0e5b7d2846a09f3a1c0e5b

mkdir -p "$OUT"
: > "$RECORD"

# Writes one row, to the record and to the terminal.
note() {
    printf '%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" >> "$RECORD"
    printf '%-8s %-26s %-8s %s\n' "$1" "$2" "$3" "$4"
}

# What one control answered, in one line. A tab in it would break the record.
#
# A test run prints one summary for each binary, and the last one is the
# doc-test summary, which is empty for most crates. The count of every summary
# is the answer there, and the last line is the answer everywhere else.
#
# The record is checked in, so a detail must name no machine. The path of this
# workspace goes, and what remains reads the same on every machine.
answer() {
    file=$OUT/$1.out
    if grep -q '^test result:' "$file" 2>/dev/null; then
        awk '/^test result:/ { passed += $4; failed += $6 }
             END { printf "%d passed, %d failed", passed, failed }' "$file"
        return
    fi
    grep -v '^[[:space:]]*$' "$file" 2>/dev/null | tail -1 | tr -d '\t' |
        sed "s|$ROOT/||g" | cut -c1-160
}

# Runs one control that must succeed.
#     run <system> <name> <command> [argument...]
run() {
    system=$1
    name=$2
    shift 2
    begin=$(date +%s)
    if "$@" > "$OUT/$name.out" 2>&1; then
        result=pass
    else
        result=fail
        FAILED=$((FAILED + 1))
    fi
    note "$system" "$name" "$result" "$(($(date +%s) - begin))s. $(answer "$name")"
}

# Runs one control that must fail, and that must say why.
#     refute <system> <name> <text it must print> <command> [argument...]
refute() {
    system=$1
    name=$2
    needle=$3
    shift 3
    begin=$(date +%s)
    if "$@" > "$OUT/$name.out" 2>&1; then
        note "$system" "$name" fail "the control succeeded, and it must not"
        FAILED=$((FAILED + 1))
    elif grep -qF "$needle" "$OUT/$name.out"; then
        note "$system" "$name" pass "$(($(date +%s) - begin))s. refused, and it said \"$needle\""
    else
        note "$system" "$name" fail "it failed for another reason than \"$needle\""
        FAILED=$((FAILED + 1))
    fi
}

skip() { note "$1" "$2" skipped "$3"; }
manual() { note "$1" "$2" manual "$3"; }

{
    printf '# generated by evidence/run.sh on %s, on %s\n' \
        "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(uname -sm)"
    printf 'system\tcontrol\tresult\tdetail\n'
} >> "$RECORD"
printf '%-8s %-26s %-8s %s\n' system control result detail

# ---------------------------------------------------------------- the toolchain

# `cargo doc` reports a broken link as a warning and exits zero, so the gate is
# the absence of a warning and not the exit status.
rustdoc() {
    output=$(cargo doc --workspace --no-deps 2>&1)
    printf '%s\n' "$output"
    ! printf '%s\n' "$output" | grep -q '^warning'
}

run host workspace-tests cargo test --workspace
run host workspace-lints cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
run host workspace-format cargo fmt --check
run host workspace-rustdoc rustdoc
for target in $TARGETS; do
    run host "cross-$target" cargo check --workspace --target "$target"
done

# ------------------------------------------------------------ guarded constants

guarded_unbound() {
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY=none \
        cargo run --quiet --example guarded -p fidelity | grep 'host: api.example.com'
}
run host guarded-unbound guarded_unbound

refute host guarded-no-signer 'IdentityBindingUnavailable' \
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY=apple:ABCDE12345 \
    cargo run --quiet --example guarded -p fidelity
refute host guarded-unnamed-kind 'names no material kind' \
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY=ABCDE12345 \
    cargo check --quiet -p fidelity
refute host guarded-wrong-platform 'reports android material' \
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY=apple:ABCDE12345 \
    cargo check --quiet -p fidelity --target aarch64-linux-android
refute host guarded-platform-without-identity 'no code identity at all' \
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY=apple:ABCDE12345 \
    cargo check --quiet -p fidelity --target aarch64-unknown-linux-gnu
# The two forms that `keytool -list -v` puts in front of a host. It separates
# every pair of digits with a colon, so the first pair reads as the kind, and it
# prints a SHA-1 digest one line above the SHA-256 one.
refute host guarded-keytool-colons 'the kind "9F"' \
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY="9F:3A:1C:0E:5B:7D:28:46" \
    cargo check --quiet -p fidelity --target aarch64-linux-android
refute host guarded-sha1-digest 'and this one has 40' \
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY="android:${DIGEST%????????????????????????}" \
    cargo check --quiet -p fidelity --target aarch64-linux-android

# The extraction ceiling. The first must recover both constants, and the second
# must recover neither, because a control that recovers with any input is
# measuring itself.
extract() {
    env FIDELITY_BUILD_SEED=test FIDELITY_CODE_IDENTITY=none \
        cargo build --release --quiet --example guarded -p fidelity || return 1
    cargo run --release --quiet --example extract -p fidelity-cipher -- \
        "$ROOT/target/release/examples/guarded" "$1" api.example.com /v1/session/open
}
run host extract-with-the-identity extract ''
refute host extract-with-another-identity 'stayed hidden' extract ABCDE12345

# `06-delivery.md` requires this one by name. The macro crate declares the seed
# with `rerun-if-env-changed`, and without that line Cargo reuses the previous
# expansion: the binary keeps the old key, and a host that rotated its seed
# ships the value it thought it had replaced. Nothing else reports that.
seeded() {
    env FIDELITY_BUILD_SEED="$1" FIDELITY_CODE_IDENTITY=none \
        cargo build --release --quiet --example guarded -p fidelity >&2 || return 1
    (shasum -a 256 2> /dev/null || sha256sum) < "$ROOT/target/release/examples/guarded" |
        cut -d' ' -f1
}
two_seeds() {
    one=$(seeded one-seed) || return 1
    another=$(seeded another-seed) || return 1
    printf 'one-seed     %s\nanother-seed %s\n' "$one" "$another"
    [ "$one" != "$another" ]
}
run host two-seeds-two-binaries two_seeds

run host sanitizers "$ROOT/evidence/controls/run-sanitizers.sh"

# `05-verification.md` puts the sanitizers on every change and Miri on a
# schedule. Miri walks seven crates and takes longer than the whole rest of this
# harness, so the default run records why it did not run rather than staying
# silent about it.
if [ "${FIDELITY_WITH_MIRI:-}" = 1 ]; then
    run host miri "$ROOT/evidence/controls/run-sanitizers.sh" just-miri
else
    skip host miri "05-verification.md schedules Miri, and it costs 4 minutes: FIDELITY_WITH_MIRI=1 evidence/run.sh"
fi

# ------------------------------------------------------- the minimum Rust version
#
# `06-delivery.md` makes the minimum version normative, and nothing checked it.
# A let-chain therefore made the claim false for months, and the workspace did
# not build on the version that it named. The version comes from the manifest
# here, so the check and the claim cannot drift apart again.
MSRV=$(sed -n 's/^rust-version = "\(.*\)"$/\1/p' "$ROOT/Cargo.toml" | head -1)
if [ -n "$MSRV" ] && rustup run "$MSRV" rustc --version > /dev/null 2>&1; then
    msrv() {
        cargo "+$MSRV" check --workspace --all-targets || return 1
        for target in $TARGETS; do
            cargo "+$MSRV" check --workspace --target "$target" || return 1
        done
        rustup run "$MSRV" rustc --version
    }
    run host "msrv-$MSRV" msrv
else
    skip host "msrv-${MSRV:-unstated}" \
        "install it first: rustup toolchain install ${MSRV:-<version>}"
fi

# ------------------------------------------------------------------------ macOS

if [ "$(uname -s)" = Darwin ]; then
    # The runtime-baseline pair. The `late` example exits zero when the worker
    # catches a change, and non-zero when the deadline passes first, so the
    # clean control is the same binary with no agent in front of it. The clean
    # half costs its whole 40 second deadline, and that wait is the measurement.
    late() {
        cargo build --quiet --example late -p fidelity || return 1
        clang -dynamiclib -o "$OUT/delayed.dylib" "$ROOT/evidence/controls/delayed.c" || return 1
        env "$@" "$ROOT/target/debug/examples/late"
    }
    baseline_hostile() { late DYLD_INSERT_LIBRARIES="$OUT/delayed.dylib"; }
    baseline_clean() { late DYLD_INSERT_LIBRARIES=; }

    # The tracer set. `lldb -b` runs the whole program under a debugger, which
    # the initial scan finds, and `lldb -p` attaches to a process that already
    # runs, which only the worker finds.
    tracer_clean() {
        cargo build --quiet --example tracer -p fidelity || return 1
        "$ROOT/target/debug/examples/tracer" | grep 'tracer_present: clean'
    }
    tracer_at_start() {
        cargo build --quiet --example tracer -p fidelity || return 1
        lldb -b -o run -- "$ROOT/target/debug/examples/tracer" |
            grep 'protected operation: denied'
    }
    tracer_attaches() {
        cargo build --quiet --example attach -p fidelity || return 1
        "$ROOT/evidence/controls/trace-after-start.sh" \
            "$ROOT/target/debug/examples/attach" lldb -p
    }

    # The region counts behind the runtime-baseline strength. `plugin-load.c`
    # includes `controls/regions.h` from the same directory.
    plugin() {
        printf 'int plugin_entry(void){return 7;}\n' > "$OUT/plug.c"
        clang -dynamiclib -o "$OUT/plugin.dylib" "$OUT/plug.c"
    }
    plugin_load() {
        plugin || return 1
        clang -I "$ROOT/evidence/controls" -o "$OUT/plugin-load" \
            "$ROOT/evidence/controls/plugin-load.c" || return 1
        counts=$("$OUT/plugin-load" "$OUT/plugin.dylib") || return 1
        printf '%s\n' "$counts"
        # A library that the dyld shared cache already holds adds no region,
        # and a plugin on disk adds one. Those two numbers decided the strength.
        printf '%s\n' "$counts" | grep -q 'shared-cache load:.*(+0)' || return 1
        printf '%s\n' "$counts" | grep -q 'plugin load.*(+1)' || return 1
    }

    # The clean control that decided the strength. A host loads one of its own
    # plugins after start, and the detector cannot tell it from an injection.
    # The same control loads a cached library, which adds no region and reports
    # nothing, and that pair is the whole argument.
    legitimate() {
        plugin || return 1
        clang -dynamiclib -o "$OUT/legitimate.dylib" \
            "$ROOT/evidence/controls/legitimate.c" || return 1
        cargo build --quiet --example late -p fidelity || return 1
        env DYLD_INSERT_LIBRARIES="$OUT/legitimate.dylib" FIDELITY_PLUGIN="$1" \
            "$ROOT/target/debug/examples/late"
    }
    legitimate_plugin() { legitimate "$OUT/plugin.dylib"; }
    legitimate_cached() { legitimate /usr/lib/libcurl.dylib; }

    run macOS cost-macos cargo run --release --quiet --example cost -p fidelity-probe-apple
    run macOS baseline-hostile baseline_hostile
    refute macOS baseline-clean 'no code arrived after start' baseline_clean
    run macOS tracer-clean tracer_clean
    run macOS tracer-at-start tracer_at_start
    run macOS tracer-attaches tracer_attaches
    run macOS plugin-load plugin_load
    run macOS legitimate-plugin legitimate_plugin
    refute macOS legitimate-cached 'no code arrived after start' legitimate_cached
else
    for control in cost-macos baseline-hostile baseline-clean \
        tracer-clean tracer-at-start tracer-attaches \
        plugin-load legitimate-plugin legitimate-cached; do
        skip macOS "$control" "this machine does not run macOS"
    done
fi

# -------------------------------------------------------------------------- iOS

SIMULATOR=$(xcrun simctl list devices 2>/dev/null | awk '/Booted/ {print $(NF-1)}' | tr -d '()' | head -1)
if [ -n "$SIMULATOR" ]; then
    ios() {
        env FIDELITY_IOS_SIM="$SIMULATOR" \
            CARGO_TARGET_AARCH64_APPLE_IOS_SIM_RUNNER="$ROOT/evidence/controls/run-ios.sh" \
            cargo "$@" --target aarch64-apple-ios-sim
    }
    run iOS ios-probe-tests ios test -p fidelity-probe-apple
    run iOS cost-ios ios run --release --quiet --example cost -p fidelity-probe-apple
else
    skip iOS ios-probe-tests "no simulator is booted: xcrun simctl boot \"iPhone 16 Pro\""
    skip iOS cost-ios "no simulator is booted"
fi

# ------------------------------------------------------------------------ Linux

# The container keeps its own target directory, in a named volume, because the
# host and the container fight over one target/ and because a cold build in a
# container costs minutes on every run.
if docker info > /dev/null 2>&1; then
    linux() {
        docker run --rm --cap-add=SYS_PTRACE \
            -v "$ROOT:/work" -w /work -v fidelity-evidence-target:/tmp/target \
            -e FIDELITY_BUILD_SEED=test -e FIDELITY_CODE_IDENTITY=none \
            -e CARGO_TARGET_DIR=/tmp/target rust:slim "$@"
    }
    # The unaccounted-code pair. A loader that maps a library from a file must
    # not trip the detector, and an agent that maps anonymous executable memory
    # must. The container ships `cc`, so it builds each agent itself.
    inject_clean() {
        linux sh -c 'cargo run --quiet --example inject -p fidelity' |
            grep 'unaccounted_code: clean'
    }
    inject_hostile() {
        linux sh -c 'cc -shared -fPIC -o /tmp/agent.so evidence/controls/agent.c &&
            LD_PRELOAD=/tmp/agent.so cargo run --quiet --example inject -p fidelity' |
            grep 'unaccounted_code: Medium'
    }
    linux_late() {
        linux sh -c "cc -shared -fPIC -o /tmp/delayed.so evidence/controls/delayed.c -lpthread &&
            cargo build --quiet --example late -p fidelity &&
            LD_PRELOAD=$1 /tmp/target/debug/examples/late"
    }
    baseline_hostile_linux() { linux_late /tmp/delayed.so; }
    baseline_clean_linux() { linux_late ''; }

    # The tracer set. The container carries no debugger, so `attach.c` is the
    # tracer, in both of its forms.
    tracer_clean_linux() {
        linux sh -c 'cargo build --quiet --example tracer -p fidelity &&
            /tmp/target/debug/examples/tracer' | grep 'tracer_present: clean'
    }
    tracer_at_start_linux() {
        linux sh -c 'cc -o /tmp/attach evidence/controls/attach.c &&
            cargo build --quiet --example tracer -p fidelity &&
            /tmp/attach /tmp/target/debug/examples/tracer' |
            grep 'protected operation: denied'
    }
    tracer_attaches_linux() {
        linux sh -c 'cc -o /tmp/attach evidence/controls/attach.c &&
            cargo build --quiet --example attach -p fidelity &&
            sh evidence/controls/trace-after-start.sh \
                /tmp/target/debug/examples/attach /tmp/attach'
    }

    run Linux linux-probe-tests linux cargo test -p fidelity-probe-linux
    run Linux cost-linux linux cargo run --release --quiet --example cost -p fidelity-probe-linux
    run Linux inject-clean inject_clean
    run Linux inject-hostile inject_hostile
    run Linux baseline-hostile-linux baseline_hostile_linux
    refute Linux baseline-clean-linux 'no code arrived after start' baseline_clean_linux
    # The same region counts. Linux holds no shared cache, so a system library
    # and a plugin each add one mapping, and the legitimate load reports.
    PLUG='printf "int plugin_entry(void){return 7;}\n" > /tmp/plug.c &&
        cc -shared -fPIC -o /tmp/plug.so /tmp/plug.c'
    plugin_load_linux() {
        counts=$(linux sh -c "$PLUG &&
            cc -o /tmp/plugin-load evidence/controls/plugin-load-linux.c -ldl &&
            /tmp/plugin-load /tmp/plug.so") || return 1
        printf '%s\n' "$counts"
        [ "$(printf '%s\n' "$counts" | grep -c '(+1)')" -eq 2 ]
    }
    legitimate_plugin_linux() {
        linux sh -c "$PLUG &&
            cc -shared -fPIC -o /tmp/legitimate.so evidence/controls/legitimate.c -ldl -lpthread &&
            cargo build --quiet --example late -p fidelity &&
            LD_PRELOAD=/tmp/legitimate.so FIDELITY_PLUGIN=/tmp/plug.so \
                /tmp/target/debug/examples/late"
    }

    run Linux tracer-clean-linux tracer_clean_linux
    run Linux tracer-at-start-linux tracer_at_start_linux
    run Linux tracer-attaches-linux tracer_attaches_linux
    run Linux plugin-load-linux plugin_load_linux
    run Linux legitimate-plugin-linux legitimate_plugin_linux
else
    for control in linux-probe-tests cost-linux inject-clean inject-hostile \
        baseline-hostile-linux baseline-clean-linux \
        tracer-clean-linux tracer-at-start-linux tracer-attaches-linux \
        plugin-load-linux legitimate-plugin-linux; do
        skip Linux "$control" "no docker daemon answers"
    done
fi

# ---------------------------------------------------------------------- Android

# Cargo links an Android binary with `cc`, which is the host compiler here, and
# the Apple linker refuses the arguments that Cargo passes. The NDK ships the
# right one under a directory that carries its version, so the harness takes the
# newest rather than a pinned path.
NDK_CC=$(ls "${ANDROID_HOME:-}"/ndk/*/toolchains/llvm/prebuilt/*/bin/aarch64-linux-android*-clang \
    2>/dev/null | tail -1)

if [ -z "$(adb devices 2>/dev/null | awk 'NR > 1 && $2 == "device" { print $1 }')" ]; then
    for control in android-probe-tests cost-android android-instrumented android-repackage; do
        skip Android "$control" "no device answers adb"
    done
elif [ -z "$NDK_CC" ]; then
    for control in android-probe-tests cost-android android-instrumented android-repackage; do
        skip Android "$control" "no NDK linker under \$ANDROID_HOME/ndk"
    done
else
    android() {
        env CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$NDK_CC" \
            CC_aarch64_linux_android="$NDK_CC" \
            CARGO_TARGET_AARCH64_LINUX_ANDROID_RUNNER="$ROOT/evidence/controls/run-android.sh" \
            cargo "$@" --target aarch64-linux-android
    }
    instrumented() {
        (cd "$ROOT/crates/probe/fidelity-probe-android/android" && ./gradlew "$@")
    }
    repackage() {
        instrumented assembleDebugAndroidTest > /dev/null 2>&1 || return 1
        (cd "$ROOT/crates/probe/fidelity-probe-android/android" &&
            "$ROOT/evidence/controls/repackage-android.sh")
    }
    run Android android-probe-tests android test -p fidelity-probe-android
    run Android cost-android android run --release --quiet --example cost -p fidelity-probe-android
    run Android android-instrumented instrumented connectedDebugAndroidTest
    run Android android-repackage repackage
fi

# The image-identity mechanism. It signs a small archive and reads the
# certificate digest from the keystore and from a walk of the signing block, so
# it needs the build tools and no device at all. The two must agree, because
# the walk is the route the probe takes and the keystore is the truth.
if [ -d "${ANDROID_HOME:-}/build-tools" ] && command -v python3 > /dev/null 2>&1; then
    run Android android-identity-mechanism "$ROOT/evidence/controls/make-apk.sh"
else
    skip Android android-identity-mechanism "no Android build tools, or no python3"
fi

# ------------------------------------------------------- what a person still runs

# Each one needs a debugger to attach, an agent to load, a judgment about a
# region count, or a second machine. None of them gives a pass or a fail on its
# own, so a person runs it and records what happened.
manual macOS controls/phases.m "the late legitimate loads table"
manual macOS controls/qos-drift.c "the worker quality of service note in 07-state-and-budgets.md"
manual iOS controls/entitle.c "the iOS identity rows, and the two recorded signatures"

printf '\n'
if [ "$FAILED" -eq 0 ]; then
    printf 'PASS: every control that this machine could run gave the answer it must give.\n'
else
    printf 'FAIL: %s control(s) gave a wrong answer. See %s/\n' "$FAILED" "$OUT"
fi
printf 'The record is %s. Its skipped rows are the work list.\n' "$RECORD"
exit "$FAILED"
