[package]
name = "fidelity-probe-linux"
description = "glibc Linux operating-system access for the fidelity runtime tamper detection library."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
fidelity-core = { path = "../../fidelity-core", version = "0.0.0" }
fidelity-formats = { path = "../../fidelity-formats", version = "0.0.0" }
fidelity-types = { path = "../../fidelity-types", version = "0.0.0" }

[lints]
workspace = true
